---
title: "Basic Ordination Methods"
subtitle: "Ordination 101 for Ecological Methods"
author: "Jari Oksanen"
date: "Nov 8 to 15, 2017"
output:
  xaringan::moon_reader:
    css: ['default', './resources/gavins.css']
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
      ratio: '16:9'
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(comment=NA,
                      echo = FALSE, message = FALSE, warning = FALSE, cache = TRUE,
                      fig.align = 'center', fig.height = 4.5, fig.width = 8, dev = 'svg')
knitr::knit_hooks$set(crop.plot = knitr::hook_pdfcrop)
options(htmltools.dir.version = FALSE)
options(rgl.useNULL=TRUE)
options(rgl.printRglwidget=FALSE)
rgl::setupKnitr()
knitr::opts_chunk$set(rgl.newwindow = TRUE)
```
```{r packages, include = FALSE, cache = FALSE}
require('vegan')
require('vegan3d')
require('rgl')
require('knitr')
```
---
# Multivariate Data

```{r lichens0, webgl = TRUE}
data(varespec)
lich <- varespec[, c("Cladstel","Cladrang","Cladarbu")]
lich <- scale(lich, scale = FALSE)
bg3d(color = "white")
clear3d()
ordirgl(lich, ax.col = "blue")
rglwidget()
```
---

# Why Ordination?

```{r pca0, webgl = TRUE}
data(varespec)
m <- rda(lich)
bg3d(color = "white")
clear3d()
ordirgl(m, scaling="site")
x <- scores(m, dis="sp", scaling="site", choices=1:3)/2
for(i in 1:3) rgl.lines(rbind(-x[i,],x[i,]), col="blue")
orgltext(x, col="blue")
rglwidget()
```

---